name: 'pr-publishing'
description: 'An action for publishing PRs'

inputs:
  artifacts-base-path:
    required: true
    description: 'Base paths for artifacts'
  self-name:
    description: 'The name of the self-user'
    default: 'github-actions[bot]'
  base-maven-url:
    description: 'The base public PR maven URL'
    default: 'https://prmaven.neoforged.net'
  uploader-workflow-name:
    required: false
    default: ''
    description: 'The name of the workflow uploading the PR artifacts'
  publishing-token:
    required: false
    description: 'The token to use for publishing'
  checkbox:
    required: false
    default: 'true'
    description: 'If set to false, all PRs made by users with write permissions to the repo will be published automatically, without being able to turn it off. PRs made by external contributors will not be published under any circumstance'

runs:
  using: node20
  main: dist/index.js
